### ISSUE TITLE
你可以尝试用“行动”功能来规定未来计划。

### ISSUE THREAD

**Issue by Shapaper** [ThirdBlood/Lhat#3]
![image](https://user-images.githubusercontent.com/88654772/163675142-88ec07d8-fa28-4fc5-b80a-b19613f38d89.png)

**Comment by ThirdBlood** [comment]
我想 GitHub Actions *不是*这样用的，也许我应当看一下。  
行动功能似乎适合用于项目自动化，而不是未来规划。
