### ISSUE TITLE
请将《客户端》/《服务端》分为两个存储库

### ISSUE THREAD

**Issue by Shapaper** [ThirdBlood/Lhat#4]

**Comment by ThirdBlood** [comment]
谢邀，该问题已在 [3rdBit存储库](https://github.com/3rdBit/Lhat/tree/LatestDev) 中解决，现在该存储库**只储存客户端**。  
与其适配的服务端是 [最新dev服务端](https://github.com/3rdBit/Lhat-Server/tree/Dev)。
